apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-config
  namespace: employee
data:
  APP_NAME: "Employee API"
  APP_VERSION: "2.0.0"
  ENVIRONMENT: "staging"
  LOG_LEVEL: "INFO"
  DATABASE_HOST: "employee-db"
