apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: employee-pvc
  namespace: employee

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 1Gi