apiVersion: v1
kind: PersistentVolume

metadata:
  name: employee-pv

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /data/employee