apiVersion: v1
kind: Secret
metadata:
  name: employee-secret
  namespace: employee
type: Opaque
stringData:
  DATABASE_USER: admin

  DATABASE_PASSWORD: password123

  JWT_SECRET: my-super-secret-key
