name: Continuous Integration

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: employee-api

jobs:

  ####################################################################
  # Quality Checks
  ####################################################################

  quality:
    name: Code Quality & Helm Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: x64
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check Code Formatting
        run: black --check .

      - name: Run Flake8
        run: flake8 .

      - name: Run Unit Tests
        run: pytest

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint helm/employee-api

      - name: Helm Template Validation
        run: helm template employee-api ./helm/employee-api

  ####################################################################
  # Build Docker Image and Scan for Vulnerabilities
  ####################################################################

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    needs: quality

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/employee-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          ####################################################################
          # Security Scan
          ####################################################################
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/employee-api:${{ github.sha }}
          format: table
          exit-code: "1"
          severity: HIGH,CRITICAL
      - name: Pushed Docker Image
        uses: docker/push-action@v6
        with:
          context: .
          push: true
          load: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/employee-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/employee-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/employee-api:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max



  ####################################################################
  # Package Helm Chart
  ####################################################################

  package:
    name: Package Helm Chart
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package Chart
        run: |
          mkdir -p dist
          helm package helm/employee-api --destination dist

      - name: Upload Helm Package
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: dist/*.tgz

  deploy:
    name: Deploy Application
    runs-on: self-hosted
    needs: package

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Verify Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v4

      # - name: Configure Kubernetes Context
      #   run: |
      #     mkdir -p ~/.kube
      #     echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy with Helm
        run: |
          helm upgrade --install employee-api ./helm/employee-api \
            --namespace employee \
            --create-namespace \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/employee-api \
            --set image.tag=${{ github.sha }}

      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/employee-api \
            -n employee \
            --timeout=180s
  smoke-test:
    name: Smoke Test
    runs-on: self-hosted

    needs: deploy

    steps:

      - name: Verify Pods
        run: |
          kubectl get pods -n employee

      - name: Check Deployment
        run: |
          kubectl rollout status deployment/employee-api \
            -n employee

      - name: Health Endpoint
        run: |
          curl --fail http://employee.local/health
  rollback:
    name: Rollback Deployment
    runs-on: self-hosted

    needs: smoke-test

    if: failure()

    steps:

      - name: Rollback Helm Release
        run: |
          helm rollback employee-api