name: Continuous Integration

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: employee-api
  RELEASE_NAME: employee-api

jobs:

  ####################################################################
  # Quality Checks
  ####################################################################

  quality:
    name: Code Quality & Helm Validation
    runs-on: employee-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: x64
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check Code Formatting
        run: black --check .

      - name: Run Flake8
        run: flake8 .

      - name: Run Unit Tests
        run: pytest

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: helm lint helm/employee-api

      - name: Helm Template Validation
        run: helm template employee-api ./helm/employee-api

  ####################################################################
  # Build Docker Image and Scan for Vulnerabilities
  ####################################################################

  build:
    name: Build Docker Image
    runs-on: employee-runner

    needs: quality

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
          
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
      - name: Pushed Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest